name: Deployment

on:
   push:
      branches: master

jobs:
   build_and_push_frontend:
      runs-on: ubuntu-22.04
      steps:
         - uses: actions/checkout@v4
           with:
              path: backend
         - uses: actions/checkout@v4
           with:
              repository: laaketeknikko/renderfrontend
              token: ${{ secrets.READ_RENDERFRONTEND }}
              path: frontend
         - name: List contents
           run: ls
         - name: List frontend contents
           run: ls frontend
