name: Deployment

on:
   push:
      branches: master

jobs:
   checkout_backend:
      runs-on: ubuntu-22.04
      steps:
         - uses: actions/checkout@v4

   checkout_frontend:
      runs-on: ubuntu-22.04
      steps:
         - uses: actions/checkout@v4
           with:
              repository: laaketeknikko/renderfrontend
              token: ${{ secrets.READ_RENDERFRONTEND }}
              path: frontend

   list_frontend_contents:
      runs-on: ubuntu-22.04
      needs: [checkout_backend, checkout_frontend]
      steps:
         - name: List contents
           run: ls
